config/routes.rb
MelanieAndScott::Application.routes.draw do
  root to: 'home#index'

  get 'about' => 'home#about'
  get 'location' => 'home#location'
  get 'directions' => 'home#directions'
  get 'registry' => 'home#registry'
  get 'accommodations' => 'home#accommodations'

  get 'update/text' => 'update#text'
  get 'update/addresses' => 'update#addresses'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def log_dbg(message)
    if Rails.env.development?
      puts "============================"
      puts message
      puts "============================"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
    
  end

  def location
    
  end

  def directions
    
  end

  def registry

  end

  def accommodations
    
  end
end

app/controllers/update_controller.rb
class UpdateController < ApplicationController
  
  def text
    log_dbg 'Logging in!'
    session = GoogleDrive.login(ENV['GOOGDR_USR'], ENV['GOOGDR_PASS'])
    log_dbg 'Getting Sheet'
    ws = session.spreadsheet_by_key(ENV['GOOGDR_SHKEY']).worksheets[0]
    log_dbg 'Reading Sheet'
    @title = ws.title
    @message = ws[1, 1]    
    @message2 = ws[2, 1]    
    @message3 = ws[3, 1]    
    @message3 = ws[3, 1]    
    @message4 = ws[4, 1]
  end

  def addresses

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<div class="row">
 
  <div class="large-6 columns">
    <%= image_tag('blazer-park.jpg') %>
  </div>
  <div class="large-6 columns">
    <h3>About Us</h3>
    <h4>Melanie</h4>
    <p>
      Melanie works as a technical recruiter at D. E. Shaw Research, a computational biochemistry group in midtown Manhattan.  Before finding her current position, she studied music and played the clarinet.  She still enjoys music of all sorts, but the karaoke bar has become her performance venue of choice.  She also enjoys cheese, running, and parades.
    </p>
    <h4>Scott</h4>
    <p>
      Scott recently transitioned from a career in the special event industry to software development. He is helping Conde Nast Entertainment launch a <a href="http://thescene.com/" target="_blank">new website</a>. You can follow the progress on <a href="https://twitter.com/SCENE" target="_blank">Twitter</a>! Previously, Scott has been a professional church musician, musical theater composer, and singing waiter. He enjoys singing Queen songs at karaoke, cycling, running, and learning new things.
    </p>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <h4>Melanie and Scott</h4>
    <p>
      Melanie and Scott met in June, 2012 at <a href="http://www.bliss47bar.com/" target="_blank">Bliss St Station</a> in Sunnyside, home of the best karaoke in the world. It was Magic Hat promotion night, complete with free beer and FREE T-SHIRTS, which for these karaoke and beer enthusiasts made for an ideal setting to get to know each other.  After some efficient and alluring post-karaoke texting, they managed to arrange a panini "hang" (deemed a date post-facto) at Il Bambino in Astoria.  They have been inseparable ever since.
    </p>
  </div>
  <div class="large-6 columns">
    <%= image_tag('present.jpg') %>
  </div>
</div>

app/views/home/accommodations.html.erb
<div class="row">
 
  <div class="large-6 columns">
    <%= image_tag('bliss-anniv.jpg') %>
  </div>
  <div class="large-6 columns">
    <h3>Accommodations</h3>
    <p>
      We have reserved a small block of rooms at the Hotel UMass for Saturday night.  For a discounted rate of $150/night (plus applicable taxes and fees), please use discount code LNWEDC.
    </p>
    <p>
      <a href="http://www.umasshotel.com/" target="_blank">Hotel UMass</a> <br>
      1 Campus Center Way <br> 
      Amherst, MA 01003
    </p>
    <p>
      <a href="http://www.lordjefferyinn.com/" target="_blank">Lord Jeffery Inn</a> (1.9 miles from Hotel UMass) <br>
      30Boltwood Ave. <br>
      Amherst, MA 01002
    </p>
    <p>
      <a href="http://www.marriott.com/hotels/travel/bdlhd-courtyard-hadley-amherst/" target="_blank">Courtyard Marriott</a> (2.4 miles from Hotel UMass) <br>
      423 Russell St. <br>
      Hadley, MA 01035
    </p>
    <p>
      <a href="http://www.ihg.com/holidayinnexpress/hotels/us/en/hadley/hdlma/hoteldetail" target="_blank">Holiday Inn Express and Suites</a> (3.6 miles from Hotel UMass) <br>
      400 Russell St. <br>
      Hadley, MA 01035
    </p>
    <p>
      <a href="http://www.redroof.com/property/South-Deerfield/MA/01373/Hotels-close-to-Yankee-Candle-Flagship-Store-I-91-US-5/RRI289/" target="_blank">Red Roof Inn</a> (8.9 miles from Hotel UMass) <br>
      9 Greenfield Rd. <br>
      South Deerfield, MA 01373
    </p>
  </div>
</div>

app/views/home/directions.html.erb
<div class="row">
  <div class="large-6 columns">
    <div class="image">
      <%= image_tag('beer-n-pumpkins.jpg') %>
    </div>
  </div>
  <div class="large-6 columns">
    <h3>Getting to Amherst</h3>
    <p>
      Amherst is located within driving distance of Bradley International Airport in Windsor Locks, CT (one hour drive) and Logan International Airport in Boston, MA (two hour drive). We recommend either renting a car or taking <a href="http://www.valleytransporter.com/" target="_blank">Valley Transporter</a> from your airport of choice to campus.
    </p>
    <p>
      It is also possible to take a train to Amherst from New York, but please note that only <a href="http://www.amtrak.com/servlet/Satellite?pagename=am/AM_Snippet_C/IBRoutes&Route=Vermonter" target="_blank">one train per day</a> travels this route, departing from Penn Station at 11:33 AM and arriving in Amherst at 4:20 PM.  Amtrak offers more regular service to Springfield, MA (30 minute drive to Amherst). 
    </p>
    <p>
      <a href="http://us.megabus.com/" target="_blank">Megabus</a> offers fairly regular service from Manhattan to Amherst.
    </p>
    <p>
      If you will not have a car in Amherst but want to explore the Pioneer Valley a bit, the <a href="http://www.pvta.com/" target="_blank">PVTA</a> is a reliable public bus service in the area.
    </p>
    <h5><strong>Parking</strong></h5>
    <p>Guests of the Hotel UMass can park for free at the Campus Center Parking Garage. There are also a number of <a href="http://parking.umass.edu/images/maps/mapVisitorParking.pdf" target="_blank">parking lots</a> near the Newman Center and the University Club that are free on weekends and after 5pm on weekdays.</p>
    <p>
      <a href="https://go.umass.edu/map/" target="_blank">Click here</a> for a UMass campus map.
    </p>
    <p>
      If you have any questions or would like more specific directions, please <a href="mailto:melanie.lahti@gmail.com">email us</a>.
    </p>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="large-6 columns">
    <div class="image">
      <!-- <h1>Melanie and Scott!</h1> -->
      <%= image_tag('mountain.jpg') %>
    </div>
  </div>
  <div class="large-6 columns">
    <h3>WELCOME</h3>
    <p>We are getting married on Saturday, October 18, 2014 in Amherst, MA.</p>
    <h5><strong>Ceremony</strong></h5>
    <p>
      <a href="http://newmanumass.org/" target="_blank">Newman Center</a> at UMass, Amherst <br>
      472 North Pleasant St. <br>
      Amherst, MA 01002
    </p>
    <p>The ceremony will begin at 2:30 PM and will last about 30 minutes. </p>
  </div>
  <div class="large-6 columns">
    
    <h5><strong>Reception</strong></h5>
    <p>
      <a href="http://www.umasshotel.com/" target="_blank">Hotel UMass</a>, Marriott Center (11th Floor) <br>
      1 Campus Center Way <br>
      Amherst, MA 01003
    </p>
    <p>
      The reception will begin at 4:00 PM and we will continue to celebrate until 9:00 PM. There will be karaoke, so bring your singing voices and/or ear plugs.
    </p>
    <p>If you're looking for something to do between the ceremony and reception, consider visiting the <a href="https://fac.umass.edu/UMCA/Online/" target="_blank">University Museum of Contemporary Art</a> (located in the Fine Arts Center, just steps away from the Newman Center), or enjoy the vantage point from the campus pond, weather permitting.</p>
    <h5><strong>Welcome Dinner *NEW VENUE*</strong></h5>
    <p>
      Friday, October 17 at 6:30 PM <br><br>
      <a href="http://www.umassuclub.com/" target="_blank">University Club and Restaurant</a> <br>
      (formerly known as the Faculty Club)<br>
      243 Stockbridge Rd. <br>
      Amherst, MA 01003
    </p>
    <p>For those of you joining us on Friday evening, we've moved our welcome dinner to the University Club and Restaurant at UMass.  The Club is housed in two colonial era New England farmhouses, one of which is the oldest house in Amherst, built in 1728.</p>
  </div>
  <div class="large-6 columns">
    <div class="image">
      <%= image_tag('snow-us.jpg') %>
    </div>
  </div> 
</div>

app/views/home/location.html.erb
<div class="row">
 
  <div class="large-8 columns">
    <%= image_tag('blazer-brunch.jpg') %>
  </div>
  <div class="large-4 columns">
    <h3>In The Area</h3>
    <h4>Outdoors</h4>
    <p>
      <a href="http://www.mohawktrail.com/hiking.html" target="_blank">Mohawk Trail</a><br>
      Various towns across the Pioneer Valley and the Berkshires
    </p>
    <p>
      <a href="http://quonquont.com/" target="_blank">Quonquont Farm</a><br>
      Whately, MA
    </p>
    <p>
      <a href="http://www.mass.gov/eea/agencies/dcr/massparks/region-west/natural-bridge-state-park-generic.html" target="_blank">Natural Bridge State Park</a><br>
      North Adams, MA
    </p>
    <p>
      <a href="http://www.thetrustees.org/places-to-visit/berkshires/monument-mountain.html" target="_blank">Monument Mountain</a><br>
      Great Barrington, MA
    </p>
    <p>
      <a href="http://www.mass.gov/eea/agencies/dcr/massparks/region-west/mt-greylock-state-reservation-generic.html" target="_blank">Mt. Greylock</a><br>
      Lanesborough, MA
    </p>
  </div>
</div>
<div class="row">
  <div class="large-6 columns">
      
    <h4>Museums</h4>
    <p>
      <a href="https://www.emilydickinsonmuseum.org/" target="_blank">Emily Dickinson Museum and Homestead</a><br>
      Amherst, MA
    </p>
    <p>
      <a href="http://www.smith.edu/artmuseum/" target="_blank">Smith College Museum of Art</a><br>
      Northampton, MA
    </p>
    <p>
      <a href="https://www.carlemuseum.org/" target="_blank">Eric Carle Museum of Picture Book Art</a><br>
      Amherst, MA
    </p>
    <p>
      <a href="http://www.nrm.org/" target="_blank">Norman Rockwell Museum</a><br>
      Stockbridge, MA
    </p>
    <p>
      <a href="http://www.massmoca.org/" target="_blank">Mass MoCA</a><br>
      North Adams, MA
    </p>
    <h4>Concert Venues</h4>
    <p>
      <a href="https://fac.umass.edu/Online/" target="_blank">UMass Fine Arts Center</a><br>
      Amherst, MA
    </p>
    <p>
      <a href="http://www.iheg.com/calvin_theater_main.asp" target="_blank">Calvin Theatre</a><br>
      Northampton, MA
    </p>
    <h4>Other Attractions<br><small>(including our favorite restaurants)</small></h4>
    <p>
      <a href="http://www.historic-deerfield.org/" target="_blank">Historic Deerfield</a><br>
      South Deerfield, MA
    </p>
    <p>
      <a href="http://www.masslive.com/news/index.ssf/2013/07/whately_mass_giant_milk_bottle.html" target="_blank">Whately Milk Bottle</a><br>
      Whately, MA
    </p>
    <p>
      <a href="http://www.yankeecandle.com/about-yankee-candle/visit-our-flagship-stores/t" target="_blank">Yankee Candle Flagship Store</a> – complete with Bavarian Christmas Village <br>
      South Deerfield, MA
    </p>
    <p>
      <a href="http://www.judiesrestaurant.com/" target="_blank">Judie’s Restaurant</a> – Home of the Popover! <br>
      Amherst, MA
    </p>
    <p>
      <a href="http://www.yelp.com/biz/raos-coffee-amherst" target="_blank">Rao’s Coffee</a><br>
      Amherst, MA
    </p>
  </div>
  <div class="large-6 columns">
    <%= image_tag('thunder-xmas.jpg') %>
  </div>
</div>

app/views/home/registry.html.erb
<div class="row">
 
  <div class="large-8 columns">
    <%= image_tag('queens-candid.jpg') %>
  </div>
  <div class="large-4 columns">
    <h3>Registry</h3>
    <p>
      We are registered at 
      <a href="http://www.macys.com/registry/wedding/guest/?registryId=6200378" target="_blank">Macy's</a> 
      and <a href="http://zola.com/registry/melanieandscott" target="_blank">Zola</a>.
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "MelanieAndScott", root_path %></h1> 
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "Directions", directions_path %></li>
      <li><%= link_to "Accommodations", accommodations_path %></li>
      <li><%= link_to "About Us", about_path %></li>
      <li><%= link_to "The Area", location_path %></li>
      <li><%= link_to "Registry", registry_path %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Melanie and Scott" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="main-container">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>